repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@^3.1.1
                - prettier-plugin-tailwindcss@^0.5.11
                - '@trivago/prettier-plugin-sort-imports@^4.3.0'
    - repo: local
      hooks:
          - id: turbo lint
            name: turbo lint
            entry: npm run lint
            language: system
            pass_filenames: false
